### ISSUE TITLE
Documentation - Swagger UI

### ISSUE THREAD

**Issue by QAInsights** [delirius325/jmeter-live-changes-config#21]
Can we have a Swagger UI for the reference or other alternatives for easy reference? E.g. https://petstore.swagger.io/

**Comment by delirius325** [comment]
Yup! Already in the roadmap 😄 !

**Comment by QAInsights** [comment]
I can take this up if you like. :)

**Comment by delirius325** [comment]
> I can take this up if you like. :)

Sure! Go for it 😄 !

**Comment by QAInsights** [comment]
@delirius325 Do you have any solution/tool in mind to create API documentation? :)

**Comment by delirius325** [comment]
@QAInsights A Swagger seems like a good idea to me!

**Comment by QAInsights** [comment]
Okay. I tried it in StopLight :) , please check the draft version. https://stoplight.io/p/docs/gh/qainsights/livechanges-api-docs

**Comment by delirius325** [comment]
Yeah looks good, keep it coming :smile: !

**Comment by QAInsights** [comment]
Added all the available APIs and its description. Could you please pass the error code sample responses?

**Comment by delirius325** [comment]
Hey there @QAInsights!

I've been doing some more work on this; I've added a `swagger.yaml` file at the root of the repo + an `index.html` that was provided via `SwaggerUI`. The swagger file is still a WIP, but there is a viewable [website](https://delirius325.github.io/jmeter-live-changes-config/) that's sourced from the `0.1.0` branch. 

I went for a swagger because I'd rather have everything as code and generated dynamically so I don't have to maintain anything else.

Cheers!
