### ISSUE TITLE
how to config the server with your project

### ISSUE THREAD

**Issue by Kitty2014** [delirius325/jmeter-live-changes-config#5]
<img width="1407" alt="conf" src="https://user-images.githubusercontent.com/7512412/53617130-d44dcf80-3c20-11e9-8f60-e861ccc68783.png">
how to config the server with your project , any Configured demo JMX file can be attached?

**Comment by delirius325** [comment]
Hi @Kitty2014 ,

So you were close.. The LiveChanges config element needs to go into the thread group itself (instead of in the sampler). There you'll be able to set a port, then start your test. Uppon the test debuting, the server will start on said port - you'll be able to communicate with it via any HTTP Client.

Thanks! 😄 

_Keep in mind this is still very much an ALPHA_

**Comment by Kitty2014** [comment]
waiting for your latest ALPHA  beta with related jmx file attached  👍👍💐💐 
By the way,https://jmeter-plugins.org/wiki/HttpSimpleTableServer/
